name: Build
on: [push]
jobs:
    Build:
        strategy:
            matrix:
                os: ["ubuntu-latest","windows-latest","macos-latest"]
        runs-on: [os]
        steps:
            - name: test
              run: echo "Hi"